{
    'name': 'Mínimos y Máximos con BI',
    'version': '1.0.0',
    'category': 'Inventory',
    'summary': 'Optimización de stock usando BI',
    'description': 'Submódulo para sugerir mínimos y máximos con base en datos históricos y análisis.',
    'author': 'enAlianza',
    'depends': ['stock', 'purchase', 'product', 'enalianza_suite', 'report_xlsx'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/minmax_menu.xml',
        'reports/minmax_report.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
